---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: astra, control center, bugs, known issues, problems 
summary: 既知の問題は、このリリースの製品を正常に使用できない可能性のある問題を特定します。 
---
= このリリースの既知の問題
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/release-notes/


既知の問題は、このリリースの製品を正常に使用できない可能性のある問題を特定します。

現在のリリースに影響する既知の問題は次のとおりです。

* <<Incorrect ClusterRoleBinding created by Astra Control Center CRD during installation>>
* <<App with user-defined label goes into "removed" state>>
* <<Unable to stop running app backup>>
* <<Backup or clone fails for apps using PVCs with decimal units in Astra Control Center>>
* <<Astra Control Center UI slow to show changes to app resources such as persistent volume changes>>
* <<During app restore from backup Trident creates a larger PV than the original PV>>
* <<Clone performance impacted by large persistent volumes>>
* <<App clones fail using a specific version of PostgreSQL>>
* <<App clones fail when using Service Account level OCP Security Context Constraints (SCC)>>
* <<S3 buckets in Astra Control Center do not report available capacity>>
* <<Reusing buckets between instances of Astra Control Center causes failures>>
* <<Selecting a bucket provider type with credentials for another type causes data protection failures>>
* <<Backups and snapshots might not be retained during removal of an Astra Control Center instance>>
* <<Extra backups are retained as part of scheduled backup>>
* link:known-issues.html#clone-operation-cant-use-other-buckets-besides-the-default["クローン処理では、デフォルト以外のバケットを使用できません"]
* <<Managing a cluster with Astra Control Center fails when default kubeconfig file contains more than one context>>
* link:known-issues.html#cant-determine-asup-tar-bundle-status-in-scaled-environment["拡張環境で ASUP tar バンドルのステータスを確認できません"]
* <<Uninstall of Astra Control Center fails to clean up the monitoring-operator pod on the managed cluster>>
* <<Uninstall of Astra Control Center fails to clean up Traefik CRDs>>
* <<ASUP collection stuck in a generating or uploading state>>




== 不正な ClusterRoleBinding が Astra Control Center CRD によってインストール中に作成されました

acc-operator バージョン 21.08.65 が導入されているすべての Kubernetes クラスタに、次のパッチを適用します。また、 acc-operator を再度展開した場合にも適用する必要があります。

この問題を解決するには：

. 以下のスクリプトの「 ACC_namespace 」を、以前使用していた名前空間に置き換えます link:../get-started/install_acc.html#install-astra-control-center["Astra Control Center の導入"]。
+
[source, cli]
----
cat <<EOF | kubectl apply -f –
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: acc-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: acc-operator-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: netapp-acc-operator
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:ACC_NAMESPACE
EOF
----
. スクリプトを実行します。


パッチは 'ClusterRoleBinding から次の 2 つの項目を削除します "acc-operator-manager-rolebinding"

[listing]
----
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
- apiGroup: ""
  kind: Group
  name: system:serviceaccounts
----


== ユーザー定義ラベルを持つアプリケーションは、「削除済み」状態になります

存在しない k8s ラベルを持つアプリケーションを定義すると、 Astra Control Center はそのアプリケーションを作成、管理し、すぐに削除します。この問題を回避するには、 Astra Control Center でアプリケーションを管理した後でポッドとリソースに Kubernetes ラベルを追加します。



== アプリケーションバックアップの実行を停止できません

実行中のバックアップを停止する方法はありません。バックアップを削除する必要がある場合は、完了するまで待ってから、の手順を実行してください link:../use/protect-apps.html#delete-backups["バックアップを削除します"]。失敗したバックアップを削除するには、を使用します link:https://docs.netapp.com/us-en/astra-automation-2108/index.html["Astra API"^]。



== Astra Control Center で 10 進数の PVC を使用しているアプリケーションのバックアップまたはクローニングが失敗する

10 進数で作成したボリュームは、 Astra Control Center のバックアップまたはクローンプロセスを使用して失敗します。を参照してください link:https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Astra/Backup_or_clone_may_fail_for_applications_using_PVCs_with_decimal_units_in_Astra_Control_Center["技術情報アーティクル"] を参照してください。



== Astra Control Center UI では、永続的ボリュームの変更などのアプリケーションリソースの変更が表示されるまでに時間がかかります

データ保護処理（クローン、バックアップ、リストア）が完了して永続ボリュームのサイズを変更したあと、新しいボリュームのサイズが UI に表示されるまでに最大 20 分かかります。この UI の遅延は、アプリケーションリソースが追加または変更された場合にも発生する可能性があります。この場合、データ保護処理が数分以内に完了し、ストレージバックエンドの管理ソフトウェアを使用してボリュームサイズの変更を確認できます。



== Trident は、バックアップからアプリケーションをリストアする際に、元の PV よりも大きな PV を作成します

バックアップの作成後に永続ボリュームのサイズを変更し、そのバックアップからリストアすると、永続ボリュームのサイズはバックアップのサイズではなく PV の新しいサイズと一致します。



== クローンのパフォーマンスが大規模な永続ボリュームによる影響を受ける

非常に大容量で消費されている永続ボリュームのクローンが、オブジェクトストアへのクラスタアクセスによって断続的に低速になる可能性があります。クローンが停止し、データが 30 分以上コピーされていない場合、 Astra Control はクローン処理を終了します。



== 特定のバージョンの PostgreSQL を使用すると、アプリケーションクローンが失敗します

Bitnami PostgreSQL 11.5.0 チャートを使用すると、同じクラスタ内のアプリケーションクローンは一貫して失敗します。正常にクローニングするには、以前のバージョンのグラフを使用してください。



== サービスアカウントレベルの OCP セキュリティコンテキスト制約（ SCC ）を使用すると、アプリケーションのクローンが失敗する

OCP クラスタのネームスペース内のサービスアカウントレベルで元のセキュリティコンテキストの制約が設定されている場合、アプリケーションのクローニングが失敗することがあります。アプリケーションのクローンが失敗すると、 Astra Control Center の管理対象アプリケーション領域にステータス「 Removed 」と表示されます。を参照してください https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Astra/Application_clone_is_failing_for_an_application_in_Astra_Control_Center["技術情報アーティクル"] を参照してください。



== Astra Control Center の S3 バケットは、使用可能容量を報告しません

Astra Control Center で管理されているアプリケーションのバックアップまたはクローニングを行う前に、 ONTAP または StorageGRID 管理システムでバケット情報を確認します。



== Astra Control Center のインスタンス間でバケットを再利用すると、障害が発生する

Astra Control Center の別のインストールまたは以前のインストールで使用していたバケットを再利用しようとすると、バックアップと復元が失敗します。別のバケットを使用するか、以前に使用したバケットを完全に消去する必要があります。Astra Control Center のインスタンス間でバケットを共有することはできません。



== 別のタイプのクレデンシャルを使用するバケットプロバイダタイプを選択すると、データ保護が失敗します

バケットを追加するときは、適切なバケットプロバイダタイプと、そのプロバイダに適したクレデンシャルを選択します。たとえば、 UI では、 StorageGRID クレデンシャルを使用して、タイプとして NetApp ONTAP S3 が受け入れられますが、これにより、今後このバケットを使用して原因のすべてのアプリケーションのバックアップとリストアが失敗します。



== Astra Control Center インスタンスの削除中にバックアップとスナップショットが保持されない場合があります

評価用ライセンスをお持ちの場合は、 Astra Control Center に障害が発生したときに ASUP を送信していないときにデータが失われないように、アカウント ID を必ず保存してください。



== 追加のバックアップはスケジュールされたバックアップの一部として保持されます

Astra Control Center の 1 つまたは複数のバックアップが、バックアップスケジュールで保持するように指定された数を超えて保持されることがあります。これらの追加バックアップは ' スケジュール・バックアップの一部として削除する必要がありますが ' 削除されず ' 保留状態になっています問題を解決するには、 https://docs.netapp.com/us-en/astra-automation-2108/workflows/wf_delete_backup.html["強制的に削除します"] 追加のバックアップ。



== クローン操作では、デフォルト以外のバケットは使用できません

アプリケーションのバックアップやリストア時に、バケット ID を必要に応じて指定することができます。ただし、アプリケーションのクローニング処理では、定義済みのデフォルトバケットが常に使用されます。クローンのバケットを変更するオプションはありません。どのバケットを使用するかを制御する必要がある場合は、どちらかを選択できます link:../use/manage-buckets.html#edit-a-bucket["バケットのデフォルト設定を変更する"] または、を実行します link:../use/protect-apps.html#create-a-backup["バックアップ"] その後にを押します link:../use/restore-apps.html["リストア"] 個別。



== デフォルトの kubeconfig ファイルに複数のコンテキストが含まれている場合、 Astra Control Center を使用したクラスタの管理が失敗します

複数のクラスタおよびコンテキストで kubeconfig を使用することはできません。を参照してください link:https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Astra/Managing_cluster_with_Astra_Control_Center_may_fail_when_using_default_kubeconfig_file_contains_more_than_one_context["技術情報アーティクル"] を参照してください。



== 拡張環境で ASUP tar バンドルのステータスを確認できません

ASUP の収集時に、 UI に表示されるバンドルのステータスは「 collecting 」または「 d one 」として報告されます。大規模な環境では、収集に最大 1 時間かかることがあります。ASUP のダウンロード中、バンドルのネットワークファイル転送速度が不十分になったり、 15 分経っても UI に何も表示されずにダウンロードがタイムアウトする場合があります。ダウンロードに関する問題は、 ASUP のサイズ、クラスタのサイズ、および収集時間が 7 日以内になるかどうかによって異なります。



== Astra Control Center をアンインストールしても、管理対象クラスタで監視オペレータポッドがクリーンアップされない

Astra Control Center をアンインストールする前にクラスタの管理を解除していない場合は、次のコマンドを使用して、ネットアップ監視ネームスペースとネームスペース内のポッドを手動で削除できます。

.手順
. 「 acc-monitoring 」エージェントを削除します。
+
[listing]
----
oc delete agents acc-monitoring -n netapp-monitoring
----
+
結果

+
[listing]
----
agent.monitoring.netapp.com "acc-monitoring" deleted
----
. ネームスペースを削除します。
+
[listing]
----
oc delete ns netapp-monitoring
----
+
結果

+
[listing]
----
namespace "netapp-monitoring" deleted
----
. リソースの削除を確認します。
+
[listing]
----
oc get pods -n netapp-monitoring
----
+
結果

+
[listing]
----
No resources found in netapp-monitoring namespace.
----
. 監視エージェントが削除されたことを確認：
+
[listing]
----
oc get crd|grep agent
----
+
サンプル結果：

+
[listing]
----
agents.monitoring.netapp.com                     2021-07-21T06:08:13Z
----
. カスタムリソース定義（ CRD ）情報の削除：
+
[listing]
----
oc delete crds agents.monitoring.netapp.com
----
+
結果

+
[listing]
----
customresourcedefinition.apiextensions.k8s.io "agents.monitoring.netapp.com" deleted
----




== Astra Control Center をアンインストールしても、 Traefik CRD をクリーンアップできない

Traefik CRD を手動で削除できます。

.手順
. アンインストールプロセスで削除されなかった CRD を確認します。
+
[listing]
----
kubectl get crds |grep -E 'traefik'
----
+
応答

+
[listing]
----
ingressroutes.traefik.containo.us             2021-06-23T23:29:11Z
ingressroutetcps.traefik.containo.us          2021-06-23T23:29:11Z
ingressrouteudps.traefik.containo.us          2021-06-23T23:29:12Z
middlewares.traefik.containo.us               2021-06-23T23:29:12Z
serverstransports.traefik.containo.us         2021-06-23T23:29:13Z
tlsoptions.traefik.containo.us                2021-06-23T23:29:13Z
tlsstores.traefik.containo.us                 2021-06-23T23:29:14Z
traefikservices.traefik.containo.us           2021-06-23T23:29:15Z
----
. CRD を削除します。
+
[listing]
----
kubectl delete crd ingressroutes.traefik.containo.us ingressroutetcps.traefik.containo.us ingressrouteudps.traefik.containo.us middlewares.traefik.containo.us serverstransports.traefik.containo.us tlsoptions.traefik.containo.us tlsstores.traefik.containo.us traefikservices.traefik.containo.us
----




== ASUP の収集が生成中またはアップロード中の状態で停止します

ASUP ポッドが強制終了されるか再起動されると、 ASUP の収集が生成中またはアップロード中の状態で停止する可能性があります。次の手順を実行します link:https://docs.netapp.com/us-en/astra-automation-2108/index.html["Astra Control REST API"] 手動収集を再開するには、次のように電話します

[cols="25,75"]
|===
| HTTP メソッド | パス 


| 投稿（ Post ） | /accounts/{accountID}/core/v1/asups 
|===

NOTE: この API 回避策は、 ASUP の起動後 10 分以上経過した場合にのみ機能します。



== 詳細については、こちらをご覧ください

* link:../release-notes/known-limitations.html["このリリースの既知の制限事項は以下のとおりです"]

